-- Exam-registration
CREATE TYPE registration_status AS ENUM (
  'NOT_STARTED',
  'STARTED',
  'PAYMENT_PENDING',
  'REGISTERED',
  'VERIFIED',
  'PAYMENT_FAILED',
  'INELIGIBLE',
  'CANCELLED'
);

-- Exam-cycle
CREATE TYPE exam_cycle_status AS ENUM (
  'DRAFT',
  'REGISTRATION_OPEN',
  'REGISTRATION_CLOSED',
  'SCHEDULED',
  'IN_PROGRESS',
  'COMPLETED',
  'RESULTS_PROCESSING',
  'RESULTS_PUBLISHED',
  'ARCHIVED'
);

-- Marks-submission
CREATE TYPE marks_status AS ENUM (
  'DRAFT',
  'UPLOADED',
  'VALIDATION_FAILED',
  'SUBMITTED',
  'VERIFIED',
  'LOCKED',
  'PUBLISHED'
);
/*
-- Payment-states 
CREATE TYPE payment_status AS ENUM (
  'PENDING',
  'PROCESSING',
  'SUCCESS',
  'FAILED',
  'REFUNDED',
  'MANUAL_VERIFICATION'
);
*/
-- Exam-type
CREATE TYPE exam_type AS ENUM (
  'END_SEMESTER',
  'MID_SEMESTER',
  'SUPPLEMENTARY',
  'BACKLOG'
);

-- Course-type
CREATE TYPE course_type AS ENUM (
  'THEORY',
  'PRACTICAL',
  'SESSIONAL'
);

-- Elective-type
CREATE TYPE elective_type AS ENUM (
  'COMPULSORY',
  'PROFESSIONAL_ELECTIVE_I',
  'PROFESSIONAL_ELECTIVE_II',
  'PROFESSIONAL_ELECTIVE_III',
  'PROFESSIONAL_ELECTIVE_II_LAB',
  'PROFESSIONAL_ELECTIVE_III_LAB',
  'OPEN_ELECTIVE_I',
  'OPEN_ELECTIVE_II'
);
